using FluentMigrator;

namespace RomanTourNotification.Infrastructure.Persistence.Migrations;

[Migration(20250130_1)]
public class CreateUserTable : Migration
{
    public override void Up()
    {
        Execute.Sql(@"
            CREATE TYPE user_role AS ENUM ('unspecified', 'developer', 'admin', 'manager')
        ");

        Execute.Sql(@"
            CREATE TABLE users (
                user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                first_name VARCHAR(50) NOT NULL,
                last_name VARCHAR(50) NOT NULL,
                user_role user_role NOT NULL,
                chat_id BIGINT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
            );
        ");
    }

    public override void Down()
    {
        Execute.Sql(@"
            DROP TABLE users;
            DROP TYPE user_role;
        ");
    }
}